"""Industrial-grade resilient parsers for extracting JSON and XML structures from LLM outputs."""

import json
import re
import xml.etree.ElementTree as ET
from typing import Any, Dict, Optional

from loguru import logger

from projects.b_prompt_engineering.src.lab_06_structured_outputs.exceptions import SyntaxParseError


class RobustJSONParser:
    """Resilient JSON parser capable of stripping markdown fences, repairing trailing commas,

    and isolating JSON payloads from conversational LLM preambles.
    """

    @staticmethod
    def strip_markdown_fences(text: str) -> str:
        """Removes markdown code fences like ```json ... ``` or ``` ..."""
        pattern = r"```(?:json)?\s*([\s\S]*?)\s*```"
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return match.group(1).strip()
        return text.strip()

    @staticmethod
    def fix_trailing_commas(json_str: str) -> str:
        """Removes illegal trailing commas before closing braces and brackets."""
        # Matches commas followed by optional whitespace and a closing brace or bracket
        fixed = re.sub(r",\s*([\]}])", r"\1", json_str)
        return fixed

    @staticmethod
    def extract_balanced_json(text: str) -> Optional[str]:
        """Finds the first balanced curly-brace or square-bracket block in text."""
        start_idx = -1
        open_char = ""
        close_char = ""

        for idx, char in enumerate(text):
            if char in ("{", "["):
                start_idx = idx
                open_char = char
                close_char = "}" if char == "{" else "]"
                break

        if start_idx == -1:
            return None

        depth = 0
        in_string = False
        escape = False

        for idx in range(start_idx, len(text)):
            c = text[idx]

            if escape:
                escape = False
                continue

            if c == "\\":
                escape = True
                continue

            if c == '"':
                in_string = not in_string
                continue

            if not in_string:
                if c == open_char:
                    depth += 1
                elif c == close_char:
                    depth -= 1
                    if depth == 0:
                        return text[start_idx : idx + 1]

        return None

    @classmethod
    def parse(cls, raw_text: str) -> Dict[str, Any]:
        """Attempts multiple recovery passes to parse raw LLM text into a dictionary."""
        cleaned = cls.strip_markdown_fences(raw_text)

        # Pass 1: Direct JSON parse
        try:
            val = json.loads(cleaned)
            if isinstance(val, dict):
                return val
            if isinstance(val, list):
                return {"items": val}
        except json.JSONDecodeError:
            pass

        # Pass 2: Trailing comma repair
        repaired = cls.fix_trailing_commas(cleaned)
        try:
            val = json.loads(repaired)
            if isinstance(val, dict):
                logger.debug("Successfully parsed JSON after trailing comma repair.")
                return val
            if isinstance(val, list):
                return {"items": val}
        except json.JSONDecodeError:
            pass

        # Pass 3: Extract balanced JSON block from conversational output
        extracted = cls.extract_balanced_json(repaired)
        if extracted:
            try:
                val = json.loads(extracted)
                if isinstance(val, dict):
                    logger.debug("Successfully parsed JSON after extracting balanced block.")
                    return val
                if isinstance(val, list):
                    return {"items": val}
            except json.JSONDecodeError:
                pass

        logger.warning("All JSON parsing recovery heuristics failed on raw input.")
        raise SyntaxParseError(
            message=f"Failed to parse valid JSON from text: {raw_text[:120]}...",
            raw_output=raw_text,
            parser_type="json",
        )


class XMLTagParser:
    """Parses XML-delimited tag outputs generated by LLMs into nested dictionaries."""

    @staticmethod
    def _element_to_data(element: ET.Element) -> Any:
        """Recursively transforms an XML element into a Python dictionary or list."""
        children = list(element)
        if not children:
            text = (element.text or "").strip()
            # Attempt primitive type casting
            if text.lower() == "true":
                return True
            if text.lower() == "false":
                return False
            if text.lower() == "none" or text.lower() == "null" or text == "":
                return None
            try:
                if "." in text:
                    return float(text)
                return int(text)
            except ValueError:
                return text

        # Check if children represent a list (e.g. repeated tags or <item> tags)
        tag_names = [child.tag for child in children]
        if all(tag == "item" for tag in tag_names) or (
            len(set(tag_names)) == 1 and len(children) > 1
        ):
            return [XMLTagParser._element_to_data(child) for child in children]

        result: Dict[str, Any] = {}
        for child in children:
            child_data = XMLTagParser._element_to_data(child)
            if child.tag in result:
                existing = result[child.tag]
                if isinstance(existing, list):
                    existing.append(child_data)
                else:
                    result[child.tag] = [existing, child_data]
            else:
                result[child.tag] = child_data
        return result

    @classmethod
    def parse(cls, raw_text: str, root_tag: Optional[str] = None) -> Dict[str, Any]:
        """Extracts and parses XML structures from text, automatically isolating root tag."""
        cleaned = RobustJSONParser.strip_markdown_fences(raw_text)

        # If a root_tag is specified, isolate it
        if root_tag:
            match = re.search(rf"<{root_tag}>([\s\S]*?)</{root_tag}>", cleaned)
            if match:
                cleaned = f"<{root_tag}>{match.group(1)}</{root_tag}>"
        else:
            # Look for any enclosing XML root tag
            match = re.search(r"<([a-zA-Z0-9_-]+)>([\s\S]*?)</\1>", cleaned)
            if match:
                root_name = match.group(1)
                cleaned = f"<{root_name}>{match.group(2)}</{root_name}>"

        try:
            root = ET.fromstring(cleaned)
            data = cls._element_to_data(root)
            if isinstance(data, dict):
                return data
            return {root.tag: data}
        except ET.ParseError as exc:
            logger.warning(f"XML parse error: {exc}")
            raise SyntaxParseError(
                message=f"Failed to parse valid XML from text: {raw_text[:120]}...",
                raw_output=raw_text,
                parser_type="xml",
            ) from exc
